import { StyleSheet } from '@react-pdf/renderer'

export const PDF_COLORS = {
  coral: '#FD4E59',
  orange: '#FFAB28',
  dark: '#161916',
  cream: '#FFF0DC',
  creamBorder: '#F5E9D7',
  white: '#FFFFFF',
  gray: '#6B7280',
  green: '#16A34A',
  genpactTint: '#FFF7ED',
}

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 11,
    color: PDF_COLORS.dark,
    paddingTop: 40,
    paddingBottom: 48,
    paddingHorizontal: 40,
    backgroundColor: PDF_COLORS.white,
  },
  pageHeader: {
    fontSize: 9,
    color: PDF_COLORS.gray,
    textAlign: 'right',
    marginBottom: 16,
  },
  pageFooter: {
    position: 'absolute',
    bottom: 22,
    left: 40,
    right: 40,
    fontSize: 9,
    color: PDF_COLORS.gray,
    textAlign: 'center',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 11,
    color: PDF_COLORS.gray,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 10,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: PDF_COLORS.gray,
    marginBottom: 8,
    marginTop: 4,
  },
  card: {
    backgroundColor: PDF_COLORS.white,
    borderWidth: 1,
    borderColor: PDF_COLORS.creamBorder,
    borderRadius: 6,
    padding: 12,
    marginBottom: 10,
  },
  heroCard: {
    backgroundColor: PDF_COLORS.cream,
    borderLeftWidth: 4,
    borderLeftColor: PDF_COLORS.coral,
    padding: 14,
    borderRadius: 6,
    marginBottom: 14,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  chip: {
    backgroundColor: '#FFF8ED',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    fontSize: 9,
    marginRight: 6,
    marginBottom: 6,
    color: PDF_COLORS.dark,
  },
  coralText: { color: PDF_COLORS.coral },
  greenText: { color: PDF_COLORS.green },
  boldText: { fontWeight: 'bold' },
  bodyText: {
    fontSize: 10,
    color: PDF_COLORS.dark,
    lineHeight: 1.45,
  },
  mutedText: {
    fontSize: 10,
    color: PDF_COLORS.gray,
    lineHeight: 1.45,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metricTile: {
    width: '48%',
    borderWidth: 1,
    borderColor: PDF_COLORS.creamBorder,
    borderRadius: 6,
    padding: 10,
    marginBottom: 8,
  },
  metricTileThird: {
    width: '31%',
    borderWidth: 1,
    borderColor: PDF_COLORS.creamBorder,
    borderRadius: 6,
    padding: 10,
    marginBottom: 8,
  },
  metricNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  metricLabel: {
    fontSize: 8,
    textTransform: 'uppercase',
    color: PDF_COLORS.gray,
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  journeyRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  journeyCard: {
    width: '31%',
    borderWidth: 1,
    borderColor: PDF_COLORS.creamBorder,
    borderRadius: 6,
    padding: 8,
    marginBottom: 6,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    borderBottomWidth: 2,
    borderBottomColor: '#D1D5DB',
    paddingVertical: 5,
    backgroundColor: '#FDF8F4',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.creamBorder,
    paddingVertical: 5,
    alignItems: 'center',
  },
  genpactRow: {
    backgroundColor: PDF_COLORS.genpactTint,
  },
  logoCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: PDF_COLORS.coral,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoImage: {
    width: 22,
    height: 22,
    objectFit: 'contain',
  },
  logoInitial: {
    fontSize: 8,
    color: PDF_COLORS.coral,
    fontWeight: 'bold',
  },
  bullet: {
    fontSize: 10,
    marginBottom: 4,
    paddingLeft: 8,
  },
  oppCard: {
    borderWidth: 1,
    borderColor: PDF_COLORS.creamBorder,
    borderRadius: 6,
    padding: 10,
    marginBottom: 8,
  },
  firstStepBox: {
    borderWidth: 1,
    borderColor: PDF_COLORS.creamBorder,
    borderRadius: 4,
    padding: 8,
    marginTop: 6,
    backgroundColor: '#FDF8F4',
  },
  callout: {
    backgroundColor: PDF_COLORS.cream,
    borderRadius: 6,
    padding: 10,
    marginTop: 8,
  },
})
